export const terms = [
  // HTML
  { name: 'div', code: '<div>Hello</div>', desc: 'Container tag. Used to group elements together. No special meaning.', source: 'local' },
  { name: 'span', code: '<span>text</span>', desc: 'Inline container. Like div but stays in same line.', source: 'local' },
  { name: 'p', code: '<p>This is text</p>', desc: 'Paragraph tag. Adds space before and after.', source: 'local' },
  { name: 'a', code: '<a href="google.com">Link</a>', desc: 'Anchor tag for links. Use href attribute.', source: 'local' },
  { name: 'img', code: '<img src="pic.jpg" alt="Photo">', desc: 'Image tag. Self-closing. Needs src and alt.', source: 'local' },
  { name: 'input', code: '<input type="text">', desc: 'Form input field. Type can be text, password, email.', source: 'local' },
  { name: 'button', code: '<button>Click Me</button>', desc: 'Clickable button.', source: 'local' },
  { name: 'form', code: '<form action="/submit">...</form>', desc: 'Form container. Wraps inputs for submission.', source: 'local' },
  { name: 'h1', code: '<h1>Title</h1>', desc: 'Largest heading. Use for main title. Goes from h1 to h6.', source: 'local' },
  { name: 'ul', code: '<ul><li>Item</li></ul>', desc: 'Unordered list. Shows bullets.', source: 'local' },
  { name: 'ol', code: '<ol><li>Item</li></ol>', desc: 'Ordered list. Shows numbers.', source: 'local' },
  { name: 'li', code: '<li>First</li>', desc: 'List item. Must be inside ul or ol.', source: 'local' },
  { name: 'head', code: '<head>...</head>', desc: 'Contains meta info, title, links to CSS. Not visible on page.', source: 'local' },
  { name: 'body', code: '<body>...</body>', desc: 'Contains all visible content on page.', source: 'local' },
  { name: 'meta', code: '<meta charset="UTF-8">', desc: 'Metadata tag. Self-closing.', source: 'local' },
  { name: 'link', code: '<link rel="stylesheet" href="style.css">', desc: 'Links external files like CSS.', source: 'local' },
  { name: 'script', code: '<script src="app.js"></script>', desc: 'Embeds JavaScript.', source: 'local' },
  { name: 'style', code: '<style>body{color:red}</style>', desc: 'Internal CSS.', source: 'local' },
  { name: 'class', code: '<div class="box"></div>', desc: 'Attribute to group elements for CSS.', source: 'local' },
  { name: 'id', code: '<div id="header"></div>', desc: 'Unique identifier for one element.', source: 'local' },
  { name: 'href', code: 'href="https://google.com"', desc: 'Attribute for a tag. Sets link URL.', source: 'local' },
  { name: 'src', code: 'src="image.png"', desc: 'Attribute for img/script. Sets source file.', source: 'local' },
  { name: 'alt', code: 'alt="Photo description"', desc: 'Alternative text for images. Shows if image fails. Important for accessibility.', source: 'local' },
  { name: 'placeholder', code: 'placeholder="Enter name"', desc: 'Hint text inside input. Disappears when user types.', source: 'local' },
  { name: 'value', code: '<input value="John">', desc: 'Current value of input.', source: 'local' },
  { name: 'disabled', code: '<button disabled>Off</button>', desc: 'Makes input/button unclickable.', source: 'local' },
  { name: 'checked', code: '<input type="checkbox" checked>', desc: 'For checkbox/radio. Makes it selected.', source: 'local' },
  { name: 'required', code: '<input required>', desc: 'Forces user to fill input before submit.', source: 'local' },
  { name: 'type', code: 'type="email"', desc: 'Defines input type. text, password, email, number, date.', source: 'local' },
  { name: 'name', code: '<input name="email">', desc: 'Name of input for form submission.', source: 'local' },
  { name: 'action', code: '<form action="/login">', desc: 'URL where form submits data.', source: 'local' },
  { name: 'method', code: 'method="POST"', desc: 'HTTP method for form. GET or POST.', source: 'local' },
  { name: 'target', code: 'target="_blank"', desc: 'Where link opens. _blank opens new tab.', source: 'local' },
  { name: 'rel', code: 'rel="noopener"', desc: 'Relationship of link. Use noopener for security.', source: 'local' },
  { name: 'data-*', code: '<div data-id="123"></div>', desc: 'Custom data attribute. Store extra info.', source: 'local' },
  { name: 'DOCTYPE', code: '<!DOCTYPE html>', desc: 'Tells browser this is HTML5. Always put at top.', source: 'local' },
  { name: 'semantic', code: '<header><nav><main></main></nav></header>', desc: 'Tags with meaning. header, footer, article, section, nav. Better than div.', source: 'local' },
  { name: 'header', code: '<header>...</header>', desc: 'Top section of page or article. Semantic tag.', source: 'local' },
  { name: 'footer', code: '<footer>...</footer>', desc: 'Bottom section of page. Semantic tag.', source: 'local' },
  { name: 'nav', code: '<nav>...</nav>', desc: 'Navigation links container. Semantic tag.', source: 'local' },
  { name: 'main', code: '<main>...</main>', desc: 'Main content of page. Only one per page. Semantic tag.', source: 'local' },
  { name: 'section', code: '<section>...</section>', desc: 'Thematic grouping of content. Semantic tag.', source: 'local' },
  { name: 'article', code: '<article>...</article>', desc: 'Self-contained content like blog post. Semantic tag.', source: 'local' },
  { name: 'aside', code: '<aside>...</aside>', desc: 'Sidebar content. Related but not main. Semantic tag.', source: 'local' },
  { name: 'canvas', code: '<canvas id="game"></canvas>', desc: 'Draw graphics with JavaScript.', source: 'local' },
  { name: 'svg', code: '<svg><circle/></svg>', desc: 'Vector graphics tag. Scales without blur.', source: 'local' },
  { name: 'iframe', code: '<iframe src="youtube.com"></iframe>', desc: 'Embed another webpage.', source: 'local' },
  { name: 'video', code: '<video src="movie.mp4" controls></video>', desc: 'Embed video.', source: 'local' },
  { name: 'audio', code: '<audio src="song.mp3" controls></audio>', desc: 'Embed audio.', source: 'local' },
  { name: 'source', code: '<source src="vid.webm">', desc: 'Multiple media sources for video/audio.', source: 'local' },
  { name: 'track', code: '<track src="subs.vtt" kind="subtitles">', desc: 'Subtitles for video.', source: 'local' },
  { name: 'figure', code: '<figure><img><figcaption>Caption</figcaption></figure>', desc: 'Groups image and caption.', source: 'local' },
  { name: 'figcaption', code: '<figcaption>Caption</figcaption>', desc: 'Caption for figure. Must be inside figure.', source: 'local' },
  { name: 'details', code: '<details><summary>Click</summary>Hidden</details>', desc: 'Collapsible content.', source: 'local' },
  { name: 'summary', code: '<summary>Click to expand</summary>', desc: 'Visible heading for details tag. Click to expand.', source: 'local' },
  { name: 'dialog', code: '<dialog open>Message</dialog>', desc: 'Popup dialog box.', source: 'local' },
  { name: 'template', code: '<template>...</template>', desc: 'HTML not rendered. Used by JavaScript to clone.', source: 'local' },

  // CSS
  { name: 'color', code: 'color: red;', desc: 'Text color.', source: 'local' },
  { name: 'background', code: 'background: blue;', desc: 'Background color or image.', source: 'local' },
  { name: 'background-color', code: 'background-color: #1e1e1e;', desc: 'Background color only.', source: 'local' },
  { name: 'background-image', code: 'background-image: url(bg.jpg);', desc: 'Background image.', source: 'local' },
  { name: 'font-size', code: 'font-size: 16px;', desc: 'Text size.', source: 'local' },
  { name: 'font-family', code: 'font-family: Arial, sans-serif;', desc: 'Font type.', source: 'local' },
  { name: 'font-weight', code: 'font-weight: bold;', desc: 'Text thickness. 400 is normal, 700 is bold.', source: 'local' },
  { name: 'text-align', code: 'text-align: center;', desc: 'Horizontal alignment. left, center, right.', source: 'local' },
  { name: 'margin', code: 'margin: 10px;', desc: 'Space outside element.', source: 'local' },
  { name: 'padding', code: 'padding: 20px;', desc: 'Space inside element.', source: 'local' },
  { name: 'border', code: 'border: 1px solid black;', desc: 'Line around element.', source: 'local' },
  { name: 'border-radius', code: 'border-radius: 8px;', desc: 'Rounded corners.', source: 'local' },
  { name: 'width', code: 'width: 100px;', desc: 'Element width.', source: 'local' },
  { name: 'height', code: 'height: 200px;', desc: 'Element height.', source: 'local' },
  { name: 'display', code: 'display: flex;', desc: 'How element shows. block, inline, flex, grid, none.', source: 'local' },
  { name: 'flex', code: 'display: flex;', desc: 'Flexbox layout. Makes children align easily.', source: 'local' },
  { name: 'flex-direction', code: 'flex-direction: column;', desc: 'Direction of flex items. row or column.', source: 'local' },
  { name: 'justify-content', code: 'justify-content: center;', desc: 'Align items horizontally in flex. center, space-between.', source: 'local' },
  { name: 'align-items', code: 'align-items: center;', desc: 'Align items vertically in flex. center, flex-start.', source: 'local' },
  { name: 'gap', code: 'gap: 10px;', desc: 'Space between flex/grid items.', source: 'local' },
  { name: 'grid', code: 'display: grid;', desc: 'Grid layout. 2D layout system.', source: 'local' },
  { name: 'grid-template-columns', code: 'grid-template-columns: 1fr 1fr;', desc: 'Defines columns in grid.', source: 'local' },
  { name: 'position', code: 'position: relative;', desc: 'Positioning type. static, relative, absolute, fixed, sticky.', source: 'local' },
  { name: 'relative', code: 'position: relative; top: 10px;', desc: 'Position relative to normal spot. Use with top, left.', source: 'local' },
  { name: 'absolute', code: 'position: absolute; top: 0;', desc: 'Position relative to nearest positioned parent.', source: 'local' },
  { name: 'fixed', code: 'position: fixed; bottom: 0;', desc: 'Position relative to screen. Stays when scrolling.', source: 'local' },
  { name: 'top', code: 'top: 20px;', desc: 'Distance from top. Use with position.', source: 'local' },
  { name: 'left', code: 'left: 0;', desc: 'Distance from left.', source: 'local' },
  { name: 'right', code: 'right: 10px;', desc: 'Distance from right.', source: 'local' },
  { name: 'bottom', code: 'bottom: 0;', desc: 'Distance from bottom.', source: 'local' },
  { name: 'z-index', code: 'z-index: 100;', desc: 'Stack order. Higher number appears on top.', source: 'local' },
  { name: 'overflow', code: 'overflow: hidden;', desc: 'What happens when content too big. hidden, scroll, auto.', source: 'local' },
  { name: 'opacity', code: 'opacity: 0.5;', desc: 'Transparency. 0 is invisible, 1 is solid.', source: 'local' },
  { name: 'box-shadow', code: 'box-shadow: 0 2px 8px rgba(0,0,0,0.5);', desc: 'Shadow around box.', source: 'local' },
  { name: 'text-shadow', code: 'text-shadow: 1px 1px 2px black;', desc: 'Shadow on text.', source: 'local' },
  { name: 'transition', code: 'transition: all 0.3s ease;', desc: 'Smooth animation between states.', source: 'local' },
  { name: 'transform', code: 'transform: scale(1.1);', desc: 'Rotate, scale, move element.', source: 'local' },
  { name: 'hover', code: 'button:hover { background: blue; }', desc: 'Pseudo-class for mouse over.', source: 'local' },
  { name: 'active', code: 'button:active { scale: 0.95; }', desc: 'Pseudo-class when element clicked.', source: 'local' },
  { name: 'focus', code: 'input:focus { border: blue; }', desc: 'Pseudo-class when element selected.', source: 'local' },
  { name: 'before', code: 'div::before { content: "→"; }', desc: 'Pseudo-element before content.', source: 'local' },
  { name: 'after', code: 'div::after { content: "✓"; }', desc: 'Pseudo-element after content.', source: 'local' },
  { name: 'media query', code: '@media (max-width: 768px) {... }', desc: 'CSS for different screen sizes.', source: 'local' },
  { name: 'rem', code: 'font-size: 1.2rem;', desc: 'Unit relative to root font size. 1rem = 16px by default. Scales well.', source: 'local' },
  { name: 'em', code: 'font-size: 2em;', desc: 'Unit relative to parent font size. 2em = 2x parent size.', source: 'local' },
  { name: 'px', code: 'width: 16px;', desc: 'Pixel unit. Fixed size.', source: 'local' },
  { name: 'vh', code: 'height: 100vh;', desc: 'Viewport height. 100vh = full screen height.', source: 'local' },
  { name: 'vw', code: 'width: 100vw;', desc: 'Viewport width. 100vw = full screen width.', source: 'local' },
  { name: '%', code: 'width: 50%;', desc: 'Percentage of parent.', source: 'local' },
  { name: 'auto', code: 'margin: 0 auto;', desc: 'Browser calculates value. Centers block.', source: 'local' },
  { name: 'inherit', code: 'color: inherit;', desc: 'Takes value from parent.', source: 'local' },
  { name: 'important', code: 'color: red!important;', desc: 'Overrides other styles. Use rarely.', source: 'local' },
  { name: 'class selector', code: '.box { color: red; }', desc: 'Targets class. Starts with dot.', source: 'local' },
  { name: 'id selector', code: '#header { height: 60px; }', desc: 'Targets id. Starts with hash.', source: 'local' },
  { name: 'tag selector', code: 'div { margin: 0; }', desc: 'Targets tag name.', source: 'local' },
  { name: 'nth-child', code: 'li:nth-child(2) { color: red; }', desc: 'Select specific child.', source: 'local' },
  { name: 'first-child', code: 'li:first-child { font-weight: bold; }', desc: 'Select first child.', source: 'local' },
  { name: 'last-child', code: 'li:last-child { border: none; }', desc: 'Select last child.', source: 'local' },
  { name: 'not', code: 'input:not([type="submit"]) { width: 100%; }', desc: 'Exclude elements.', source: 'local' },
  { name: 'calc', code: 'width: calc(100% - 20px);', desc: 'Do math in CSS.', source: 'local' },
  { name: 'var', code: 'color: var(--hye-blue);', desc: 'CSS variable.', source: 'local' },
  { name: 'root', code: ':root { --hye-blue: #007acc; }', desc: 'Declare CSS variables.', source: 'local' },

  // JavaScript
  { name: 'var', code: 'var x = 5;', desc: 'Old way to declare variable. Function scoped. Avoid.', source: 'local' },
  { name: 'let', code: 'let count = 0;', desc: 'Declare variable that can change. Block scoped.', source: 'local' },
  { name: 'const', code: 'const API = "url";', desc: 'Declare constant that cannot change. Block scoped.', source: 'local' },
  { name: 'function', code: 'function add(a,b) { return a+b }', desc: 'Block of code you can call.', source: 'local' },
  { name: 'arrow function', code: 'const add = (a,b) => a+b', desc: 'Short function syntax.', source: 'local' },
  { name: 'return', code: 'return 42;', desc: 'Sends value back from function. Stops function.', source: 'local' },
  { name: 'if', code: 'if (x > 5) { console.log("big") }', desc: 'Run code if condition true.', source: 'local' },
  { name: 'else', code: 'else { console.log("small") }', desc: 'Run if condition false.', source: 'local' },
  { name: 'else if', code: 'else if(x>5){}', desc: 'Check another condition.', source: 'local' },
  { name: 'switch', code: 'switch(day) { case "Mon":... break; }', desc: 'Check many values.', source: 'local' },
  { name: 'for', code: 'for(let i=0; i<5; i++) { console.log(i) }', desc: 'Loop code multiple times.', source: 'local' },
  { name: 'while', code: 'while(x<10) { x++ }', desc: 'Loop while condition true.', source: 'local' },
  { name: 'break', code: 'if(i===5) break;', desc: 'Exit loop early.', source: 'local' },
  { name: 'continue', code: 'if(i===5) continue;', desc: 'Skip to next loop iteration.', source: 'local' },
  { name: 'array', code: 'const arr = [1,2,3];', desc: 'List of items.', source: 'local' },
  { name: 'object', code: 'const user = { name: "John", age: 20 };', desc: 'Key-value pairs.', source: 'local' },
  { name: 'string', code: 'const name = "HYE";', desc: 'Text data. Use quotes.', source: 'local' },
  { name: 'number', code: 'const age = 25;', desc: 'Numeric data.', source: 'local' },
  { name: 'boolean', code: 'const isOnline = true;', desc: 'True or false.', source: 'local' },
  { name: 'null', code: 'let data = null;', desc: 'Intentional empty value.', source: 'local' },
  { name: 'undefined', code: 'let x; console.log(x);', desc: 'Variable declared but no value.', source: 'local' },
  { name: 'typeof', code: 'typeof "hello"', desc: 'Check data type. Returns "string"', source: 'local' },
  { name: 'length', code: '"HYE".length', desc: 'Size of array or string. Returns 3', source: 'local' },
  { name: 'push', code: 'arr.push(4);', desc: 'Add item to end of array.', source: 'local' },
  { name: 'pop', code: 'arr.pop();', desc: 'Remove last item from array.', source: 'local' },
  { name: 'shift', code: 'arr.shift();', desc: 'Remove first item from array.', source: 'local' },
  { name: 'unshift', code: 'arr.unshift(0);', desc: 'Add item to start of array.', source: 'local' },
  { name: 'map', code: 'arr.map(x => x*2)', desc: 'Create new array by transforming each item.', source: 'local' },
  { name: 'filter', code: 'arr.filter(x => x>5)', desc: 'Create new array with items that pass test.', source: 'local' },
  { name: 'reduce', code: 'arr.reduce((sum,x) => sum+x, 0)', desc: 'Combine array to single value.', source: 'local' },
  { name: 'forEach', code: 'arr.forEach(x => console.log(x))', desc: 'Run function for each item. No return.', source: 'local' },
  { name: 'find', code: 'arr.find(x => x>5)', desc: 'Get first item that passes test.', source: 'local' },
  { name: 'includes', code: 'arr.includes(3)', desc: 'Check if array/string contains item.', source: 'local' },
  { name: 'indexOf', code: 'arr.indexOf(3)', desc: 'Find position of item. Returns -1 if not found.', source: 'local' },
  { name: 'slice', code: 'arr.slice(1,3)', desc: 'Copy part of array.', source: 'local' },
  { name: 'splice', code: 'arr.splice(1,1)', desc: 'Add/remove items in array. Changes original.', source: 'local' },
  { name: 'split', code: '"a,b,c".split(",")', desc: 'Split string into array. Returns ["a","b","c"]', source: 'local' },
  { name: 'join', code: '["a","b"].join("-")', desc: 'Join array into string. Returns "a-b"', source: 'local' },
  { name: 'JSON.parse', code: 'JSON.parse(\'{"a":1}\')', desc: 'Convert JSON string to object.', source: 'local' },
  { name: 'JSON.stringify', code: 'JSON.stringify({a:1})', desc: 'Convert object to JSON string.', source: 'local' },
  { name: 'setTimeout', code: 'setTimeout(() => console.log("Hi"), 1000)', desc: 'Run code after delay.', source: 'local' },
  { name: 'setInterval', code: 'setInterval(() => console.log("tick"), 1000)', desc: 'Run code repeatedly.', source: 'local' },
  { name: 'clearInterval', code: 'clearInterval(timerId)', desc: 'Stop setInterval.', source: 'local' },
  { name: 'addEventListener', code: 'btn.addEventListener("click", fn)', desc: 'Listen for events like click.', source: 'local' },
  { name: 'removeEventListener', code: 'btn.removeEventListener("click", fn)', desc: 'Stop listening.', source: 'local' },
  { name: 'preventDefault', code: 'e.preventDefault()', desc: 'Stop default browser action. Used in form submit', source: 'local' },
  { name: 'stopPropagation', code: 'e.stopPropagation()', desc: 'Stop event bubbling up.', source: 'local' },
  { name: 'querySelector', code: 'document.querySelector(".box")', desc: 'Get first matching element.', source: 'local' },
  { name: 'querySelectorAll', code: 'document.querySelectorAll("button")', desc: 'Get all matching elements.', source: 'local' },
  { name: 'getElementById', code: 'document.getElementById("header")', desc: 'Get element by id.', source: 'local' },
  { name: 'innerHTML', code: 'div.innerHTML = "<b>Hi</b>"', desc: 'Get/set HTML inside element.', source: 'local' },
  { name: 'innerText', code: 'div.innerText = "Hi"', desc: 'Get/set text inside element.', source: 'local' },
  { name: 'classList', code: 'div.classList.add("active")', desc: 'Manage classes.', source: 'local' },
  { name: 'add', code: 'div.classList.add("show")', desc: 'Add class.', source: 'local' },
  { name: 'remove', code: 'div.classList.remove("show")', desc: 'Remove class.', source: 'local' },
  { name: 'toggle', code: 'div.classList.toggle("dark")', desc: 'Add if missing, remove if present.', source: 'local' },
  { name: 'contains', code: 'div.classList.contains("active")', desc: 'Check if class exists.', source: 'local' },
  { name: 'localStorage', code: 'localStorage.setItem("key","value")', desc: 'Store data in browser. Persists. 5MB limit.', source: 'local' },
  { name: 'sessionStorage', code: 'sessionStorage.setItem("key","value")', desc: 'Store data until tab closed.', source: 'local' },
  { name: 'getItem', code: 'localStorage.getItem("key")', desc: 'Read from storage.', source: 'local' },
  { name: 'setItem', code: 'localStorage.setItem("key","value")', desc: 'Write to storage.', source: 'local' },
  { name: 'removeItem', code: 'localStorage.removeItem("key")', desc: 'Delete from storage.', source: 'local' },
  { name: 'fetch', code: 'fetch("/api/data").then(r=>r.json())', desc: 'Make HTTP request. Returns promise.', source: 'local' },
  { name: 'async', code: 'async function getData() {}', desc: 'Marks function as async. Use with await.', source: 'local' },
  { name: 'await', code: 'const data = await fetch(url)', desc: 'Wait for promise. Only in async function.', source: 'local' },
  { name: 'try', code: 'try { risky() }', desc: 'Wrap code that might fail.', source: 'local' },
  { name: 'catch', code: 'catch(e) { console.error(e) }', desc: 'Handle error from try.', source: 'local' },
  { name: 'finally', code: 'finally { cleanup() }', desc: 'Run after try/catch always.', source: 'local' },
  { name: 'throw', code: 'throw new Error("Failed")', desc: 'Create error.', source: 'local' },
  { name: 'Promise', code: 'new Promise((resolve,reject) => {})', desc: 'Object for async result.', source: 'local' },
  { name: 'then', code: 'fetch().then(res => res.json())', desc: 'Handle promise success.', source: 'local' },
  { name: 'new', code: 'const date = new Date()', desc: 'Create instance of class.', source: 'local' },
  { name: 'this', code: 'this.name', desc: 'Refers to current object. Context dependent.', source: 'local' },
  { name: 'class', code: 'class User { constructor(name) { this.name = name } }', desc: 'Blueprint for objects.', source: 'local' },
  { name: 'constructor', code: 'constructor() { this.x = 0 }', desc: 'Runs when class instance created.', source: 'local' },
  { name: 'extends', code: 'class Admin extends User {}', desc: 'Inherit from another class.', source: 'local' },
  { name: 'super', code: 'super(name)', desc: 'Call parent class constructor.', source: 'local' },
  { name: 'import', code: 'import React from "react"', desc: 'Bring code from other file.', source: 'local' },
  { name: 'export', code: 'export const x = 5', desc: 'Make code available to other files.', source: 'local' },
  { name: 'default', code: 'export default App', desc: 'Default export. Only one per file.', source: 'local' },
  { name: 'destructure', code: 'const {name} = user', desc: 'Extract values from object/array.', source: 'local' },
  { name: 'spread', code: 'const newArr = [...arr, 4]', desc: 'Expand array/object.', source: 'local' },
  { name: 'rest', code: 'function sum(...nums) {}', desc: 'Collect remaining items.', source: 'local' },
  { name: 'template literal', code: '`Hello \${name}`', desc: 'String with variables. Use backticks.', source: 'local' },
  { name: 'ternary', code: 'const msg = age>18? "Adult" : "Kid"', desc: 'Short if/else.', source: 'local' },
  { name: '&&', code: 'isLoggedIn && showUser()', desc: 'AND operator. Returns first falsy or last truthy.', source: 'local' },
  { name: '||', code: 'const name = user.name || "Guest"', desc: 'OR operator. Returns first truthy.', source: 'local' },
  { name: '??', code: 'const x = y?? 0', desc: 'Nullish coalescing. Returns right if left is null/undefined.', source: 'local' },
  { name: '?.', code: 'user?.address?.city', desc: 'Optional chaining. Safe access.', source: 'local' },
  { name: '===', code: '5 === "5"', desc: 'Strict equal. Checks value and type. Returns false', source: 'local' },
  { name: '==', code: '5 == "5"', desc: 'Loose equal. Converts type. Avoid. Returns true', source: 'local' },
  { name: '!==', code: '5!== "5"', desc: 'Strict not equal. Returns true', source: 'local' },
  { name: '!=', code: '5!= "5"', desc: 'Loose not equal. Avoid. Returns false', source: 'local' },
  { name: 'callback', code: 'arr.map(callback)', desc: 'Function passed to another function.', source: 'local' },
  { name: 'closure', code: 'function outer() { let x=0; return () => x++ }', desc: 'Function remembers outer variables.', source: 'local' },
  { name: 'hoisting', code: '// var and function declarations moved to top', desc: 'var and function declarations moved to top. let/const not hoisted.', source: 'local' },
  { name: 'scope', code: '// Global, function, block', desc: 'Where variable is accessible. Global, function, block.', source: 'local' },
  { name: 'event', code: 'button.addEventListener("click", e => {})', desc: 'Action like click, keypress.', source: 'local' },
  { name: 'debounce', code: '// Delay function until user stops', desc: 'Delay function until user stops. Good for search input.', source: 'local' },
  { name: 'throttle', code: '// Limit function to run once per time', desc: 'Limit function to run once per time. Good for scroll.', source: 'local' },
  { name: 'IIFE', code: '(function(){})()', desc: 'Immediately Invoked Function Expression.', source: 'local' },
  { name: 'NaN', code: '"abc" * 2', desc: 'Not a Number. Result of invalid math.', source: 'local' },
  { name: 'isNaN', code: 'isNaN("abc")', desc: 'Check if value is NaN. Returns true', source: 'local' },

  // React
  { name: 'useState', code: 'const [count, setCount] = useState(0)', desc: 'Hook to add state.', source: 'local' },
  { name: 'useEffect', code: 'useEffect(() => { fetchData() }, [])', desc: 'Hook to run side effects.', source: 'local' },
  { name: 'useRef', code: 'const inputRef = useRef()', desc: 'Hook to keep value across renders or reference DOM.', source: 'local' },
  { name: 'useCallback', code: 'const fn = useCallback(() => {}, [])', desc: 'Hook to memoize function.', source: 'local' },
  { name: 'useMemo', code: 'const val = useMemo(() => heavy(), [])', desc: 'Hook to memoize value.', source: 'local' },
  { name: 'useContext', code: 'const theme = useContext(ThemeContext)', desc: 'Hook to use context.', source: 'local' },
  { name: 'useReducer', code: 'const [state, dispatch] = useReducer(reducer, init)', desc: 'Hook for complex state. Like Redux.', source: 'local' },
  { name: 'useLayoutEffect', code: 'useLayoutEffect(() => {}, [])', desc: 'Like useEffect but runs before paint. Use for DOM measurements.', source: 'local' },
  { name: 'props', code: 'function Button(props) { return <button>{props.text}</button> }', desc: 'Data passed to component. Read-only.', source: 'local' },
  { name: 'state', code: 'const [val, setVal] = useState(0)',desc: 'Data owned by component. Can change. Use useState.', source: 'local' },
  { name: 'component', code: 'function App() { return <div>Hi</div> }', desc: 'Reusable UI piece. Function that returns JSX.', source: 'local' },
  { name: 'JSX', code: 'const el = <h1>Hello</h1>', desc: 'Syntax for React. Looks like HTML in JS.', source: 'local' },
  { name: 'key', code: '<li key={item.id}>', desc: 'Special prop for lists. Helps React track items.', source: 'local' },
  { name: 'Fragment', code: '<> <h1>Title</h1> <p>Text</p> </>', desc: 'Groups elements without extra div.', source: 'local' },
  { name: 'children', code: '<Card> <p>Child</p> </Card>', desc: 'Content between component tags.', source: 'local' },
  { name: 'defaultProps', code: 'Button.defaultProps = { color: "blue" }', desc: 'Default values for props.', source: 'local' },
  { name: 'propTypes', code: 'Button.propTypes = { text: PropTypes.string }', desc: 'Type checking for props.', source: 'local' },
  { name: 'controlled', code: '<input value={val} onChange={e=>setVal(e.target.value)}>', desc: 'Input value controlled by React state.', source: 'local' },
  { name: 'uncontrolled', code: '<input ref={inputRef}>', desc: 'Input value controlled by DOM. Use ref.', source: 'local' },
  { name: 'event', code: '<button onClick={handleClick}>', desc: 'React events like onClick, onChange.', source: 'local' },
  { name: 'SyntheticEvent', code: 'e.preventDefault()', desc: 'React wrapper around native event. Cross-browser consistent.', source: 'local' },
  { name: 'lifecycle', code: 'useEffect(() => {}, [])', desc: 'Stages of component: mount, update, unmount. useEffect handles all.', source: 'local' },
  { name: 'mount', code: 'useEffect(() => {}, [])', desc: 'Component first renders. useEffect with [] runs here.', source: 'local' },
  { name: 'unmount', code: 'useEffect(() => { return () => clearInterval(id) }, [])', desc: 'Component removed. Cleanup in useEffect return.', source: 'local' },
  { name: 'update', code: '// runs when props/state change', desc: 'Component re-renders when props or state change.', source: 'local' },
  { name: 'render', code: 'return <div>...</div>', desc: 'Function that returns JSX. Runs on every state/prop change.', source: 'local' },
  { name: 'virtual DOM', code: '// React internal', desc: 'React creates JS copy of DOM. Diffs and updates real DOM efficiently.', source: 'local' },
  { name: 'reconciliation', code: '// React diffing process', desc: 'Process React uses to update DOM by comparing virtual DOM trees.', source: 'local' },
  { name: 'memo', code: 'export default memo(Component)', desc: 'Higher order component to skip re-render if props same.', source: 'local' },
  { name: 'forwardRef', code: 'const Input = forwardRef((props, ref) => <input ref={ref}>)', desc: 'Pass ref through component.', source: 'local' },
  { name: 'createContext', code: 'const ThemeContext = createContext()', desc: 'Create context for global state.', source: 'local' },
  { name: 'Provider', code: '<ThemeContext.Provider value={theme}>', desc: 'Wrap app to provide context.', source: 'local' },
  { name: 'lazy', code: 'const Page = lazy(() => import("./Page"))', desc: 'Code split component. Load when needed.', source: 'local' },
  { name: 'Suspense', code: '<Suspense fallback={<Spinner>}> <Page/> </Suspense>', desc: 'Show fallback while lazy loads.', source: 'local' },
  { name: 'error boundary', code: 'class ErrorBoundary extends React.Component { componentDidCatch() {} }', desc: 'Component that catches JS errors in children. Class component with componentDidCatch.', source: 'local' },
  { name: 'portal', code: 'createPortal(<Modal/>, document.body)', desc: 'Render children outside DOM hierarchy.', source: 'local' },
  { name: 'StrictMode', code: '<StrictMode><App/></StrictMode>', desc: 'Dev tool that checks for problems.', source: 'local' },
  { name: 'hook rules', code: '// 1. Only at top level 2. Only from React functions', desc: '1. Only call hooks at top level. 2. Only call from React functions.', source: 'local' },
  { name: 'custom hook', code: 'function useFetch(url) {}', desc: 'Function starting with use that calls other hooks.', source: 'local' },
  { name: 'useId', code: 'const id = useId()', desc: 'Generate unique id for accessibility.', source: 'local' },
  { name: 'useTransition', code: 'const [isPending, startTransition] = useTransition()', desc: 'Mark state update as non-urgent.', source: 'local' },
  { name: 'useDeferredValue', code: 'const deferredQuery = useDeferredValue(query)', desc: 'Defer updating part of UI.', source: 'local' },

  // Node
  { name: 'require', code: 'const fs = require("fs")', desc: 'Import module in CommonJS.', source: 'local' },
  { name: 'module.exports', code: 'module.exports = { add }', desc: 'Export from CommonJS.', source: 'local' },
  { name: 'exports', code: 'exports.add = add', desc: 'Shorthand for module.exports.', source: 'local' },
  { name: 'process', code: 'process.env.PORT', desc: 'Global object with info about Node process.', source: 'local' },
  { name: 'env', code: 'process.env.NODE_ENV', desc: 'Environment variables.', source: 'local' },
  { name: 'argv', code: 'process.argv[2]', desc: 'Command line arguments.', source: 'local' },
  { name: 'cwd', code: 'process.cwd()', desc: 'Current working directory.', source: 'local' },
  { name: 'exit', code: 'process.exit(1)', desc: 'Exit process.', source: 'local' },
  { name: 'Buffer', code: 'const buf = Buffer.from("hello")', desc: 'Handle binary data.', source: 'local' },
  { name: 'fs', code: 'fs.readFileSync("file.txt")', desc: 'File system module.', source: 'local' },
  { name: 'readFile', code: 'fs.readFile("file.txt", (err,data) => {})', desc: 'Read file async.', source: 'local' },
  { name: 'readFileSync', code: 'const data = fs.readFileSync("file.txt")', desc: 'Read file sync. Blocks.', source: 'local' },
  { name: 'writeFile', code: 'fs.writeFile("file.txt", "hi", err => {})', desc: 'Write file async.', source: 'local' },
  { name: 'path', code: 'path.join(__dirname, "file.txt")', desc: 'Work with file paths.', source: 'local' },
  { name: 'join', code: 'path.join("folder","file.txt")', desc: 'Join path segments.', source: 'local' },
  { name: 'resolve', code: 'path.resolve("file.txt")', desc: 'Resolve to absolute path.', source: 'local' },
  { name: 'dirname', code: 'path.dirname("/a/b/c.txt")', desc: 'Directory name of path. Returns "/a/b"', source: 'local' },
  { name: 'basename', code: 'path.basename("/a/b.txt")', desc: 'File name from path. Returns "b.txt"', source: 'local' },
  { name: 'extname', code: 'path.extname("file.txt")', desc: 'File extension. Returns ".txt"', source: 'local' },
  { name: 'http', code: 'http.createServer((req,res) => {})', desc: 'Create HTTP server.', source: 'local' },
  { name: 'express', code: 'const app = express()', desc: 'Web framework.', source: 'local' },
  { name: 'app.get', code: 'app.get("/", (req,res) => res.send("Hi"))', desc: 'Handle GET request.', source: 'local' },
  { name: 'app.post', code: 'app.post("/login", (req,res) => {})', desc: 'Handle POST request.', source: 'local' },
  { name: 'app.use', code: 'app.use(express.json())', desc: 'Add middleware.', source: 'local' },
  { name: 'req', code: 'req.params.id', desc: 'Request object. Has params, query, body.', source: 'local' },
  { name: 'res', code: 'res.json({success:true})', desc: 'Response object. Send data back.', source: 'local' },
  { name: 'next', code: 'next()', desc: 'Call next middleware.', source: 'local' },
  { name: 'middleware', code: 'app.use(logger)', desc: 'Function that runs between request and response.', source: 'local' },
  { name: 'cors', code: 'app.use(cors())', desc: 'Enable cross-origin requests.', source: 'local' },
  { name: 'dotenv', code: 'require("dotenv").config()', desc: 'Load.env file.', source: 'local' },
  { name: 'nodemon', code: 'nodemon server.js', desc: 'Auto restart server on file change. Use in dev.', source: 'local' },
  { name: 'npm', code: 'npm install express', desc: 'Node package manager. Install packages.', source: 'local' },
  { name: 'package.json', code: '{ "dependencies": { "express": "^4.18.0" } }', desc: 'Project config file. Lists dependencies and scripts.', source: 'local' },
  { name: 'node_modules', code: '// folder with packages', desc: 'Folder where npm installs packages. Never commit.', source: 'local' },
  { name: 'async', code: 'async function getData() {}', desc: 'Function returns promise.', source: 'local' },
  { name: 'await', code: 'const data = await fetch()', desc: 'Wait for promise in async function.', source: 'local' },
  { name: 'callback', code: 'fs.readFile(file, callback)', desc: 'Function passed to run later.', source: 'local' },
  { name: 'Promise', code: 'new Promise((resolve,reject) => {})', desc: 'Object for async value.', source: 'local' },
  { name: 'EventEmitter', code: 'emitter.on("event", fn); emitter.emit("event")', desc: 'Pub/sub pattern.', source: 'local' },
  { name: 'stream', code: 'fs.createReadStream("big.txt")', desc: 'Handle large data piece by piece.', source: 'local' },
  { name: 'pipe', code: 'readStream.pipe(writeStream)', desc: 'Connect streams.', source: 'local' },
  { name: 'child_process', code: 'exec("ls", (err,stdout) => {})', desc: 'Run other programs.', source: 'local' },
  { name: 'cluster', code: 'cluster.fork()', desc: 'Run multiple Node processes. Use all CPU cores.', source: 'local' },
  { name: 'worker_threads', code: 'new Worker("./worker.js")', desc: 'Run JS in parallel threads. For CPU heavy tasks.', source: 'local' },
  { name: 'crypto', code: 'crypto.createHash("sha256")', desc: 'Cryptography module. Hash, encrypt.', source: 'local' },
  { name: 'os', code: 'os.cpus()', desc: 'Operating system info.', source: 'local' },
  { name: 'util', code: 'util.promisify(fs.readFile)', desc: 'Utilities.', source: 'local' },
  { name: 'url', code: 'new URL("https://site.com/path")', desc: 'Parse URLs.', source: 'local' },
  { name: 'querystring', code: 'querystring.parse("a=1&b=2")', desc: 'Parse query strings.', source: 'local' },
  { name: 'zlib', code: 'zlib.gzip(buffer, callback)', desc: 'Compress data.', source: 'local' },
  { name: 'assert', code: 'assert(x===5)', desc: 'Test assumptions. Throws if false.', source: 'local' },
  { name: 'events', code: 'const EventEmitter = require("events")', desc: 'Built-in event module.', source: 'local' },
  { name: 'timers', code: 'setTimeout, setInterval, setImmediate', desc: 'Built-in timing functions.', source: 'local' },
  { name: 'global', code: 'global.myVar = 1', desc: 'Global object in Node. Like window in browser.', source: 'local' },
  { name: '__dirname', code: 'path.join(__dirname, "file")', desc: 'Directory of current file.', source: 'local' },
  { name: '__filename', code: 'console.log(__filename)', desc: 'Path of current file.', source: 'local' },

  // Git
  { name: 'git init', code: 'git init', desc: 'Start new git repo in folder.', source: 'local' },
  { name: 'git clone', code: 'git clone https://github.com/user/repo.git', desc: 'Copy remote repo to local.', source: 'local' },
  { name: 'git add', code: 'git add.', desc: 'Stage files for commit. Use. for all or filename.', source: 'local' },
  { name: 'git commit', code: 'git commit -m "Fix bug"', desc: 'Save staged changes with message.', source: 'local' },
  { name: 'git push', code: 'git push origin main', desc: 'Send commits to remote.', source: 'local' },
  { name: 'git pull', code: 'git pull origin main', desc: 'Get latest changes from remote.', source: 'local' },
  { name: 'git fetch', code: 'git fetch origin', desc: 'Download remote changes but do not merge.', source: 'local' },
  { name: 'git merge', code: 'git merge feature', desc: 'Combine branches.', source: 'local' },
  { name: 'git branch', code: 'git branch new-feature', desc: 'List, create, or delete branches.', source: 'local' },
  { name: 'git checkout', code: 'git checkout main', desc: 'Switch branch or restore files.', source: 'local' },
  { name: 'git switch', code: 'git switch main', desc: 'New way to switch branch.', source: 'local' },
  { name: 'git status', code: 'git status', desc: 'Show changed files.', source: 'local' },
  { name: 'git log', code: 'git log --oneline', desc: 'Show commit history.', source: 'local' },
  { name: 'git diff', code: 'git diff', desc: 'Show changes between commits/files.', source: 'local' },
  { name: 'git reset', code: 'git reset --hard HEAD~1', desc: 'Undo commits. --hard deletes changes.', source: 'local' },
  { name: 'git revert', code: 'git revert HEAD', desc: 'Undo commit by creating new commit. Safe.', source: 'local' },
  { name: 'git stash', code: 'git stash', desc: 'Save changes temporarily.', source: 'local' },
  { name: 'git stash pop', code: 'git stash pop', desc: 'Restore stashed changes.', source: 'local' },
  { name: 'git remote', code: 'git remote -v', desc: 'Manage remote repos.', source: 'local' },
  { name: 'git remote add', code: 'git remote add origin https://github.com/user/repo.git', desc: 'Add remote.', source: 'local' },
  { name: 'git tag', code: 'git tag v1.0.0', desc: 'Mark release point.', source: 'local' },
  { name: 'git rebase', code: 'git rebase main', desc: 'Move commits to new base. Rewrite history.', source: 'local' },
  { name: 'git cherry-pick', code: 'git cherry-pick abc123', desc: 'Copy one commit to current branch.', source: 'local' },
  { name: 'HEAD', code: 'HEAD~1', desc: 'Points to current commit. HEAD~1 means one commit back.', source: 'local' },
  { name: 'origin', code: 'git push origin main', desc: 'Default name for remote repo.', source: 'local' },
  { name: 'main', code: 'git switch main', desc: 'Default branch name. Old name was master.', source: 'local' },
  { name: 'master', code: '// old name for main', desc: 'Old default branch name. Now main.', source: 'local' },
  { name: '.gitignore', code: 'node_modules/', desc: 'File listing files git should ignore.', source: 'local' },
  { name: 'merge conflict', code: '<<<<<<< HEAD', desc: 'When git cannot auto-merge. You must fix manually.', source: 'local' },
  { name: 'pull request', code: '// GitHub UI', desc: 'Ask to merge your branch. GitHub/GitLab term. Short: PR', source: 'local' },
  { name: 'fork', code: '// Click Fork on GitHub', desc: 'Your copy of someone else repo on GitHub.', source: 'local' },
  { name: 'upstream', code: 'git remote add upstream...', desc: 'Original repo you forked from.', source: 'local' },
  { name: 'fast-forward', code: '// no merge commit', desc: 'Merge when no new commits on target branch. No merge commit created.', source: 'local' },
  { name: 'rebase vs merge', code: '// merge keeps history, rebase linear', desc: 'Merge keeps history, rebase makes linear. Rebase rewrites history.', source: 'local' },
  { name: 'detached HEAD', code: 'git checkout abc123', desc: 'HEAD not on branch. Happens after checkout commit. Do not commit here.', source: 'local' },
  { name: 'git bisect', code: 'git bisect start', desc: 'Find commit that introduced bug using binary search.', source: 'local' },
  { name: 'git blame', code: 'git blame index.js', desc: 'Show who changed each line of file.', source: 'local' },
  { name: 'git clean', code: 'git clean -fd', desc: 'Remove untracked files. Dangerous.', source: 'local' },
  { name: 'git config', code: 'git config --global user.name "HYE"', desc: 'Set git options.', source: 'local' },
  { name: 'SSH key', code: 'ssh-keygen -t ed25519', desc: 'Secure way to connect to GitHub. No password needed.', source: 'local' },
  { name: 'PAT', code: 'ghp_xxx', desc: 'Personal Access Token. Used instead of password for GitHub.', source: 'local' },

  // TypeScript
  { name: 'type', code: 'type User = { name: string; age: number }', desc: 'Define shape of data.', source: 'local' },
  { name: 'interface', code: 'interface User { name: string }', desc: 'Like type but can be extended.', source: 'local' },
  { name: 'extends', code: 'interface Admin extends User { role: string }', desc: 'Inherit from interface/type.', source: 'local' },
  { name: 'any', code: 'let data: any = 5', desc: 'Disable type checking. Avoid.', source: 'local' },
  { name: 'unknown', code: 'let x: unknown = 5', desc: 'Like any but safer. Must check type before use.', source: 'local' },
  { name: 'never', code: 'function error(): never { throw new Error() }', desc: 'Function never returns.', source: 'local' },
  { name: 'void', code: 'function log(): void { console.log("hi") }', desc: 'Function returns nothing.', source: 'local' },
  { name: 'null', code: 'let x: string | null = null', desc: 'Intentional empty. Type: null.', source: 'local' },
  { name: 'undefined', code: 'let x: number | undefined', desc: 'Variable not set. Type: undefined.', source: 'local' },
  { name: 'union', code: 'let id: string | number', desc: 'Value can be multiple types. Use |.', source: 'local' },
  { name: 'intersection', code: 'type Admin = User & { role: string }', desc: 'Combine types. Use &.', source: 'local' },
  { name: 'generic', code: 'function identity<T>(arg: T): T { return arg }', desc: 'Reusable type with placeholder.', source: 'local' },
  { name: 'T', code: 'Array<T>', desc: 'Common name for generic type. Can be any letter.', source: 'local' },
  { name: 'keyof', code: 'keyof User', desc: 'Get keys of type as union. Returns "name" | "age"', source: 'local' },
  { name: 'typeof', code: 'type X = typeof user', desc: 'Get type of variable.', source: 'local' },
  { name: 'in', code: 'type Keys = "a" | "b"; type Obj = { [K in Keys]: string }', desc: 'Check if key in object type. Used in mapped types.', source: 'local' },
  { name: 'Partial', code: 'Partial<User>', desc: 'Make all properties optional.', source: 'local' },
  { name: 'Required', code: 'Required<User>', desc: 'Make all properties required.', source: 'local' },
  { name: 'Readonly', code: 'Readonly<User>', desc: 'Make all properties readonly.', source: 'local' },
  { name: 'Record', code: 'Record<string, number>', desc: 'Object type with specific keys and value.', source: 'local' },
  { name: 'Pick', code: 'Pick<User, "name">', desc: 'Choose properties from type.', source: 'local' },
  { name: 'Omit', code: 'Omit<User, "age">', desc: 'Remove properties from type.', source: 'local' },
  { name: 'Exclude', code: 'Exclude<"a"|"b"|"c", "a">', desc: 'Remove types from union. Returns "b"|"c"', source: 'local' },
  { name: 'Extract', code: 'Extract<"a"|"b"|"c", "a">', desc: 'Keep only types in union. Returns "a"', source: 'local' },
  { name: 'NonNullable', code: 'NonNullable<string|null>', desc: 'Remove null and undefined.', source: 'local' },
  { name: 'ReturnType', code: 'ReturnType<typeof fn>', desc: 'Get return type of function.', source: 'local' },
  { name: 'Parameters', code: 'Parameters<typeof fn>', desc: 'Get parameter types of function as tuple.', source: 'local' },
  { name: 'enum', code: 'enum Color { Red, Blue }', desc: 'Set of named constants.', source: 'local' },
  { name: 'as', code: 'const el = document.getElementById("x") as HTMLInputElement', desc: 'Type assertion. Tell TS the type.', source: 'local' },
  { name: 'is', code: 'function isUser(x: any): x is User {}', desc: 'Type predicate for custom type guard.', source: 'local' },
  { name: 'implements', code: 'class Admin implements User {}', desc: 'Class must match interface.', source: 'local' },
  { name: 'public', code: 'public name: string', desc: 'Class property accessible anywhere. Default.', source: 'local' },
  { name: 'private', code: 'private id: string', desc: 'Class property only inside class.', source: 'local' },
  { name: 'protected', code: 'protected age: number', desc: 'Class property inside class and subclasses.', source: 'local' },
  { name: 'readonly', code: 'readonly id: string', desc: 'Property cannot be changed after init.', source: 'local' },
  { name: 'abstract', code: 'abstract class Animal {}', desc: 'Class that cannot be instantiated.', source: 'local' },
  { name: 'namespace', code: 'namespace Utils {}', desc: 'Group code. Old. Use modules now.', source: 'local' },
  { name: 'declare', code: 'declare const VERSION: string', desc: 'Tell TS about global variable.', source: 'local' },
  { name: 'd.ts', code: 'index.d.ts', desc: 'Type definition file.', source: 'local' },
  { name: 'tsconfig.json', code: '{ "compilerOptions": { "strict": true } }', desc: 'TS compiler config. Sets rules like target, module, strict.', source: 'local' },
  { name: 'target', code: '"target": "ES2020"', desc: 'JS version to compile to.', source: 'local' },
  { name: 'module', code: '"module": "ESNext"', desc: 'Module system. CommonJS, ESNext.', source: 'local' },
  { name: 'strict', code: '"strict": true', desc: 'Enable all strict checks. Recommended true.', source: 'local' },
  { name: 'noImplicitAny', code: '"noImplicitAny": true', desc: 'Error when type is any. Good to enable.', source: 'local' },
  { name: 'jsx', code: '"jsx": "react-jsx"', desc: 'How to compile JSX. For React use "react-jsx"', source: 'local' },
  { name: 'baseUrl', code: '"baseUrl": "./src"', desc: 'Base directory for imports.', source: 'local' },
  { name: 'paths', code: '"paths": { "@/*": ["src/*"] }', desc: 'Map import aliases.', source: 'local' },
  { name: 'include', code: '"include": ["src"]', desc: 'Files to compile.', source: 'local' },
  { name: 'exclude', code: '"exclude": ["node_modules"]', desc: 'Files to skip.', source: 'local' },
  { name: 'lib', code: '"lib": ["ES2020", "DOM"]', desc: 'Built-in API types to include.', source: 'local' },
  { name: 'skipLibCheck', code: '"skipLibCheck": true', desc: 'Skip checking.d.ts files. Faster builds. Set true.', source: 'local' },
  { name: 'esModuleInterop', code: '"esModuleInterop": true', desc: 'Better import for CommonJS. Set true.', source: 'local' },
  { name: 'allowSyntheticDefaultImports', code: '"allowSyntheticDefaultImports": true', desc: 'Allow import React from "react". Set true.', source: 'local' },

  // Python
  { name: 'def', code: 'def add(a, b): return a + b', desc: 'Define function.', source: 'local' },
  { name: 'class', code: 'class User: pass', desc: 'Define class.', source: 'local' },
  { name: 'self', code: 'self.name = name', desc: 'Reference to instance. Like this in JS.', source: 'local' },
  { name: '__init__', code: 'def __init__(self, name):', desc: 'Constructor method. Runs when object created.', source: 'local' },
  { name: 'import', code: 'import os', desc: 'Bring module.', source: 'local' },
  { name: 'from', code: 'from math import sqrt', desc: 'Import specific from module.', source: 'local' },
  { name: 'as', code: 'import numpy as np', desc: 'Rename import.', source: 'local' },
  { name: 'if', code: 'if x > 5: print("big")', desc: 'Conditional.', source: 'local' },
  { name: 'elif', code: 'elif x>5:...', desc: 'Else if.', source: 'local' },
  { name: 'else', code: 'else: print("small")', desc: 'Fallback.', source: 'local' },
  { name: 'for', code: 'for i in range(5): print(i)', desc: 'Loop over sequence.', source: 'local' },
  { name: 'while', code: 'while x < 10: x += 1', desc: 'Loop while true.', source: 'local' },
  { name: 'break', code: 'if i==5: break', desc: 'Exit loop.', source: 'local' },
  { name: 'continue', code: 'if i==5: continue', desc: 'Skip iteration.', source: 'local' },
  { name: 'pass', code: 'if True: pass', desc: 'Do nothing. Placeholder.', source: 'local' },
  { name: 'return', code: 'return x * 2', desc: 'Return value from function.', source: 'local' },
  { name: 'lambda', code: 'add = lambda a,b: a+b', desc: 'Anonymous function.', source: 'local' },
  { name: 'list', code: 'arr = [1, 2, 3]', desc: 'Ordered mutable collection.', source: 'local' },
  { name: 'tuple', code: 'point = (10, 20)', desc: 'Ordered immutable collection.', source: 'local' },
  { name: 'dict', code: 'user = {"name": "John", "age": 20}', desc: 'Key-value pairs.', source: 'local' },
  { name: 'set', code: 's = {1, 2, 3}', desc: 'Unordered unique items.', source: 'local' },
  { name: 'len', code: 'len([1,2,3])', desc: 'Get size. Returns 3', source: 'local' },
  { name: 'append', code: 'arr.append(4)', desc: 'Add to end of list.', source: 'local' },
  { name: 'pop', code: 'arr.pop()', desc: 'Remove and return last item.', source: 'local' },
  { name: 'insert', code: 'arr.insert(0, 5)', desc: 'Add at index.', source: 'local' },
  { name: 'remove', code: 'arr.remove(2)', desc: 'Remove first matching value.', source: 'local' },
  { name: 'sort', code: 'arr.sort()', desc: 'Sort list in place.', source: 'local' },
  { name: 'sorted', code: 'sorted(arr)', desc: 'Return new sorted list.', source: 'local' },
  { name: 'range', code: 'range(5)', desc: 'Generate numbers. 0,1,2,3,4', source: 'local' },
  { name: 'enumerate', code: 'for i, val in enumerate(arr):', desc: 'Loop with index.', source: 'local' },
  { name: 'zip', code: 'for a,b in zip(list1, list2):', desc: 'Combine lists.', source: 'local' },
  { name: 'in', code: 'if 3 in arr:', desc: 'Check if item in collection.', source: 'local' },
  { name: 'not in', code: 'if 5 not in arr:', desc: 'Check if item not in collection.', source: 'local' },
  { name: 'is', code: 'x is None', desc: 'Check if same object.', source: 'local' },
  { name: 'is not', code: 'x is not None', desc: 'Check if not same object.', source: 'local' },
  { name: 'None', code: 'x = None', desc: 'Null value in Python.', source: 'local' },
  { name: 'True', code: 'flag = True', desc: 'Boolean true. Capital T.', source: 'local' },
  { name: 'False', code: 'flag = False', desc: 'Boolean false. Capital F.', source: 'local' },
  { name: 'and', code: 'if x>5 and x<10:', desc: 'Logical AND.', source: 'local' },
  { name: 'or', code: 'if x<5 or x>10:', desc: 'Logical OR.', source: 'local' },
  { name: 'not', code: 'if not active:', desc: 'Logical NOT.', source: 'local' },
  { name: 'try', code: 'try: risky()', desc: 'Wrap risky code.', source: 'local' },
  { name: 'except', code: 'except Exception as e: print(e)', desc: 'Catch error.', source: 'local' },
  { name: 'finally', code: 'finally: cleanup()', desc: 'Always run.', source: 'local' },
  { name: 'raise', code: 'raise ValueError("Bad")', desc: 'Throw error.', source: 'local' },
  { name: 'with', code: 'with open("f.txt") as f: data = f.read()', desc: 'Auto cleanup. Used for files.', source: 'local' },
  { name: 'open', code: 'f = open("file.txt", "r")', desc: 'Open file.', source: 'local' },
  { name: 'read', code: 'data = f.read()', desc: 'Read file content.', source: 'local' },
  { name: 'write', code: 'f.write("hello")', desc: 'Write to file.', source: 'local' },
  { name: 'close', code: 'f.close()', desc: 'Close file.', source: 'local' },
  { name: 'list comprehension', code: 'squares = [x*x for x in range(10)]', desc: 'Short way to create list.', source: 'local' },
  { name: 'dict comprehension', code: '{x: x*x for x in range(5)}', desc: 'Short way to create dict.', source: 'local' },
  { name: 'f-string', code: 'name="HYE"; print(f"Hello {name}")', desc: 'Formatted string.', source: 'local' },
  { name: 'split', code: '"a,b,c".split(",")', desc: 'Split string to list. Returns ["a","b","c"]', source: 'local' },
  { name: 'join', code: '",".join(["a","b"])', desc: 'Join list to string. Returns "a,b"', source: 'local' },
  { name: 'strip', code: '" hi ".strip()', desc: 'Remove whitespace.', source: 'local' },
  { name: 'replace', code: '"hello".replace("l","x")', desc: 'Replace text.', source: 'local' },
  { name: 'format', code: '"Hello {}".format("HYE")', desc: 'Insert into string.', source: 'local' },
  { name: 'int', code: 'int("5")', desc: 'Convert to integer.', source: 'local' },
  { name: 'str', code: 'str(5)', desc: 'Convert to string.', source: 'local' },
  { name: 'float', code: 'float("5.5")', desc: 'Convert to decimal.', source: 'local' },
  { name: 'list', code: 'list("abc")', desc: 'Convert to list. Returns ["a","b","c"]', source: 'local' },
  { name: 'dict', code: 'dict([("a",1),("b",2)])', desc: 'Convert to dict.', source: 'local' },
  { name: 'type', code: 'type(5)', desc: 'Get type of object. Returns <class "int">', source: 'local' },
  { name: 'isinstance', code: 'isinstance(5, int)', desc: 'Check type. Returns True', source: 'local' },
  { name: 'pip', code: 'pip install requests', desc: 'Python package installer.', source: 'local' },
  { name: 'requirements.txt', code: 'pip install -r requirements.txt', desc: 'List of packages.', source: 'local' },
  { name: 'venv', code: 'python -m venv venv', desc: 'Virtual environment. Isolate packages.', source: 'local' },
  { name: 'main', code: 'if __name__ == "__main__": run()', desc: 'Entry point check.', source: 'local' },
  { name: 'decorator', code: '@app.route("/")', desc: 'Wrap function. Uses @.', source: 'local' },
  { name: 'generator', code: 'def gen(): yield 1; yield 2', desc: 'Function with yield. Lazy values.', source: 'local' },
  { name: 'yield', code: 'yield 1', desc: 'Return value but keep state. Used in generators.', source: 'local' },

  // SQL
  { name: 'SELECT', code: 'SELECT * FROM users', desc: 'Get data from table.', source: 'local' },
  { name: 'FROM', code: 'FROM users', desc: 'Specify table.', source: 'local' },
  { name: 'WHERE', code: 'WHERE age > 18', desc: 'Filter rows.', source: 'local' },
  { name: 'INSERT', code: 'INSERT INTO users (name) VALUES ("John")', desc: 'Add new row.', source: 'local' },
  { name: 'UPDATE', code: 'UPDATE users SET age = 21 WHERE id = 1', desc: 'Change existing row.', source: 'local' },
  { name: 'DELETE', code: 'DELETE FROM users WHERE id = 1', desc: 'Remove rows.', source: 'local' },
  { name: 'CREATE TABLE', code: 'CREATE TABLE users (id INT, name TEXT)', desc: 'Make new table.', source: 'local' },
  { name: 'ALTER TABLE', code: 'ALTER TABLE users ADD email TEXT', desc: 'Change table structure.', source: 'local' },
  { name: 'DROP TABLE', code: 'DROP TABLE users', desc: 'Delete table.', source: 'local' },
  { name: 'PRIMARY KEY', code: 'id INT PRIMARY KEY', desc: 'Unique identifier for row.', source: 'local' },
  { name: 'FOREIGN KEY', code: 'FOREIGN KEY (user_id) REFERENCES users(id)', desc: 'Link to another table.', source: 'local' },
  { name: 'NOT NULL', code: 'name TEXT NOT NULL', desc: 'Column cannot be empty.', source: 'local' },
  { name: 'UNIQUE', code: 'email TEXT UNIQUE', desc: 'All values in column must be different.', source: 'local' },
  { name: 'DEFAULT', code: 'created_at TIMESTAMP DEFAULT NOW()', desc: 'Default value if none given.', source: 'local' },
  { name: 'INDEX', code: 'CREATE INDEX idx_email ON users(email)', desc: 'Speed up searches.', source: 'local' },
  { name: 'JOIN', code: 'SELECT * FROM orders JOIN users ON orders.user_id = users.id', desc: 'Combine rows from tables.', source: 'local' },
  { name: 'INNER JOIN', code: 'SELECT * FROM a INNER JOIN b ON a.id=b.id', desc: 'Only matching rows from both tables. Default JOIN.', source: 'local' },
  { name: 'LEFT JOIN', code: 'SELECT * FROM a LEFT JOIN b ON a.id=b.id', desc: 'All from left table, matching from right.', source: 'local' },
  { name: 'RIGHT JOIN', code: 'SELECT * FROM a RIGHT JOIN b ON a.id=b.id', desc: 'All from right table, matching from left.', source: 'local' },
  { name: 'GROUP BY', code: 'SELECT age, COUNT(*) FROM users GROUP BY age', desc: 'Group rows for aggregation.', source: 'local' },
  { name: 'HAVING', code: 'HAVING COUNT(*) > 5', desc: 'Filter groups. Like WHERE but for groups.', source: 'local' },
  { name: 'ORDER BY', code: 'ORDER BY created_at DESC', desc: 'Sort results.', source: 'local' },
  { name: 'LIMIT', code: 'LIMIT 10', desc: 'Limit number of rows.', source: 'local' },
  { name: 'OFFSET', code: 'LIMIT 10 OFFSET 20', desc: 'Skip rows. Used for pagination.', source: 'local' },
  { name: 'COUNT', code: 'SELECT COUNT(*) FROM users', desc: 'Count rows.', source: 'local' },
  { name: 'SUM', code: 'SELECT SUM(price) FROM orders', desc: 'Add values.', source: 'local' },
  { name: 'AVG', code: 'SELECT AVG(age) FROM users', desc: 'Average value.', source: 'local' },
  { name: 'MAX', code: 'SELECT MAX(price) FROM products', desc: 'Highest value.', source: 'local' },
  { name: 'MIN', code: 'SELECT MIN(price) FROM products', desc: 'Lowest value.', source: 'local' },
  { name: 'DISTINCT', code: 'SELECT DISTINCT city FROM users', desc: 'Remove duplicates.', source: 'local' },
  { name: 'LIKE', code: 'WHERE name LIKE "J%"', desc: 'Pattern match. % is wildcard.', source: 'local' },
  { name: 'IN', code: 'WHERE id IN (1,2,3)', desc: 'Match any in list.', source: 'local' },
  { name: 'BETWEEN', code: 'WHERE age BETWEEN 18 AND 30', desc: 'Range match.', source: 'local' },
  { name: 'IS NULL', code: 'WHERE email IS NULL', desc: 'Check for null.', source: 'local' },
  { name: 'IS NOT NULL', code: 'WHERE email IS NOT NULL', desc: 'Check for not null.', source: 'local' },
  { name: 'AS', code: 'SELECT name AS username FROM users', desc: 'Rename column or table.', source: 'local' },
  { name: 'UNION', code: 'SELECT name FROM a UNION SELECT name FROM b', desc: 'Combine results from two queries. Removes duplicates.', source: 'local' },
  { name: 'UNION ALL', code: 'SELECT name FROM a UNION ALL SELECT name FROM b', desc: 'Combine results, keep duplicates.', source: 'local' },
  { name: 'CASE', code: 'SELECT CASE WHEN age>18 THEN "Adult" ELSE "Kid" END', desc: 'If/else in SQL.', source: 'local' },
  { name: 'WITH', code: 'WITH cte AS (...) SELECT * FROM cte', desc: 'Common Table Expression. Temporary result.', source: 'local' },
  { name: 'EXISTS', code: 'WHERE EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)', desc: 'Check if subquery returns rows.', source: 'local' },
  { name: 'TRANSACTION', code: 'BEGIN; ... COMMIT;', desc: 'Group queries. All succeed or all fail.', source: 'local' },
  { name: 'BEGIN', code: 'BEGIN', desc: 'Start transaction.', source: 'local' },
  { name: 'COMMIT', code: 'COMMIT', desc: 'Save transaction changes.', source: 'local' },
  { name: 'ROLLBACK', code: 'ROLLBACK', desc: 'Undo transaction changes.', source: 'local' },
  { name: 'VIEW', code: 'CREATE VIEW adults AS SELECT * FROM users WHERE age>18', desc: 'Saved query. Like virtual table.', source: 'local' },
  { name: 'TRIGGER', code: 'AFTER INSERT ON users', desc: 'Auto run on event.', source: 'local' },
  { name: 'FUNCTION', code: 'CREATE FUNCTION get_age() RETURNS INT', desc: 'Reusable SQL code.', source: 'local' },
  { name: 'PROCEDURE', code: 'CREATE PROCEDURE update_stats()', desc: 'Like function but can run transactions.', source: 'local' },
  { name: 'GRANT', code: 'GRANT SELECT ON users TO readonly_user', desc: 'Give permission.', source: 'local' },
  { name: 'REVOKE', code: 'REVOKE SELECT ON users FROM readonly_user', desc: 'Remove permission.', source: 'local' },
  { name: 'EXPLAIN', code: 'EXPLAIN SELECT * FROM users', desc: 'Show query plan. Use to debug slow queries.', source: 'local' },
  { name: 'VACUUM', code: 'VACUUM', desc: 'Clean up database. PostgreSQL specific.', source: 'local' },
  { name: 'uuid', code: 'gen_random_uuid()', desc: 'Universally unique ID.', source: 'local' },
  { name: 'timestamp', code: 'created_at TIMESTAMP DEFAULT NOW()', desc: 'Date and time.', source: 'local' },
  { name: 'jsonb', code: 'data JSONB', desc: 'Binary JSON column. PostgreSQL. Queryable.', source: 'local' },
  { name: 'serial', code: 'id SERIAL PRIMARY KEY', desc: 'Auto-increment integer. PostgreSQL.', source: 'local' },

  // General Dev
  { name: 'API', code: 'fetch("/api/users")', desc: 'Application Programming Interface. Way for apps to talk. Example: REST API', source: 'local' },
  { name: 'REST', code: 'GET /api/users', desc: 'API style using HTTP methods. GET, POST, PUT, DELETE.', source: 'local' },
  { name: 'endpoint', code: '/api/users', desc: 'URL for API.', source: 'local' },
  { name: 'JSON', code: '{"name":"HYE"}', desc: 'JavaScript Object Notation. Data format.', source: 'local' },
  { name: 'HTTP', code: 'GET /index.html HTTP/1.1', desc: 'Protocol for web. Browser and server talk with it.', source: 'local' },
  { name: 'GET', code: 'GET /api/users', desc: 'HTTP method to read data.', source: 'local' },
  { name: 'POST', code: 'POST /api/users', desc: 'HTTP method to create data.', source: 'local' },
  { name: 'PUT', code: 'PUT /api/users/1', desc: 'HTTP method to update all data.', source: 'local' },
  { name: 'PATCH', code: 'PATCH /api/users/1', desc: 'HTTP method to update part of data.', source: 'local' },
  { name: 'DELETE', code: 'DELETE /api/users/1', desc: 'HTTP method to remove data.', source: 'local' },
  { name: 'status code', code: '200 OK', desc: 'Number telling result. 200=OK, 404=Not Found, 500=Server Error', source: 'local' },
  { name: '200', code: 'HTTP/1.1 200 OK', desc: 'OK. Request succeeded.', source: 'local' },
  { name: '201', code: 'HTTP/1.1 201 Created', desc: 'Created. New resource made.', source: 'local' },
  { name: '400', code: 'HTTP/1.1 400 Bad Request', desc: 'Bad Request. Client error.', source: 'local' },
  { name: '401', code: 'HTTP/1.1 401 Unauthorized', desc: 'Unauthorized. Need login.', source: 'local' },
  { name: '403', code: 'HTTP/1.1 403 Forbidden', desc: 'Forbidden. No permission.', source: 'local' },
  { name: '404', code: 'HTTP/1.1 404 Not Found', desc: 'Not Found. URL does not exist.', source: 'local' },
  { name: '500', code: 'HTTP/1.1 500 Internal Server Error', desc: 'Internal Server Error. Server bug.', source: 'local' },
  { name: 'CORS', code: 'Access-Control-Allow-Origin: *', desc: 'Cross-Origin Resource Sharing. Browser security. Server must allow it.', source: 'local' },
  { name: 'JWT', code: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...', desc: 'JSON Web Token. Used for auth. Signed string with user data.', source: 'local' },
  { name: 'auth', code: 'login(email, password)', desc: 'Authentication. Prove who you are. Login.', source: 'local' },
  { name: 'authorization', code: 'if(user.role === "admin")', desc: 'Permission. What you can do after login.', source: 'local' },
  { name: 'hash', code: 'bcrypt.hash(password, 10)', desc: 'One-way encryption. For passwords.', source: 'local' },
  { name: 'salt', code: 'bcrypt.genSalt(10)', desc: 'Random data added to password before hash. Prevents rainbow table attack.', source: 'local' },
  { name: 'cookie', code: 'Set-Cookie: session=abc123', desc: 'Data stored in browser by server. Sent with every request.', source: 'local' },
  { name: 'session', code: 'req.session.userId = 1', desc: 'Server-side storage for user data. Uses cookie for id.', source: 'local' },
  { name: 'localStorage', code: 'localStorage.setItem("key","value")', desc: 'Browser storage. Persists. 5MB limit.', source: 'local' },
  { name: 'sessionStorage', code: 'sessionStorage.setItem("key","value")', desc: 'Browser storage. Cleared on tab close.', source: 'local' },
  { name: 'cache', code: 'Cache-Control: max-age=3600', desc: 'Store data to load faster next time.', source: 'local' },
  { name: 'CDN', code: '<script src="https://cdn.jsdelivr.net/...">', desc: 'Content Delivery Network. Servers worldwide to serve files fast. Example: Cloudflare', source: 'local' },
  { name: 'DNS', code: 'nslookup google.com', desc: 'Domain Name System. Converts domain to IP. Example: google.com to 142.250.185.46', source: 'local' },
  { name: 'IP', code: '192.168.1.1', desc: 'Internet Protocol address. Unique device address.', source: 'local' },
  { name: 'localhost', code: 'http://localhost:3000', desc: 'Your computer. IP: 127.0.0.1', source: 'local' },
  { name: 'port', code: 'localhost:3000', desc: 'Number for specific service. HTTP=80, HTTPS=443.', source: 'local' },
  { name: 'SSL', code: '// old name for TLS', desc: 'Secure Sockets Layer. Encrypts connection. Old name for TLS.', source: 'local' },
  { name: 'TLS', code: '// new name for SSL', desc: 'Transport Layer Security. New name for SSL. HTTPS uses this.', source: 'local' },
  { name: 'HTTPS', code: 'https://site.com', desc: 'HTTP with TLS. Secure. Shows padlock in browser.', source: 'local' },
  { name: 'WebSocket', code: 'new WebSocket("wss://site.com")', desc: 'Persistent connection for real-time. Example: chat apps', source: 'local' },
  { name: 'OAuth', code: 'Login with Google', desc: 'Login with Google/GitHub. You give permission to app.', source: 'local' },
  { name: 'npm', code: 'npm install express', desc: 'Node Package Manager. Install JS packages.', source: 'local' },
  { name: 'yarn', code: 'yarn add express', desc: 'Alternative to npm. Faster sometimes.', source: 'local' },
  { name: 'pnpm', code: 'pnpm add express', desc: 'Alternative to npm. Saves disk space.', source: 'local' },
  { name: 'bundler', code: 'vite build', desc: 'Combines files for browser. Examples: Vite, Webpack, Rollup', source: 'local' },
  { name: 'Vite', code: 'npm create vite@latest', desc: 'Fast bundler. Used in HYE. Dev server + build.', source: 'local' },
  { name: 'Webpack', code: 'webpack.config.js', desc: 'Popular bundler. Complex config.', source: 'local' },
  { name: 'Babel', code: '.babelrc', desc: 'Convert new JS to old JS for old browsers.', source: 'local' },
  { name: 'ESLint', code: 'eslint .', desc: 'Find problems in JS code. Linter.', source: 'local' },
  { name: 'Prettier', code: 'prettier --write .', desc: 'Format code automatically. Makes code consistent.', source: 'local' },
  { name: 'CI/CD', code: '.github/workflows/deploy.yml', desc: 'Continuous Integration/Deployment. Auto test and deploy. Example: GitHub Actions', source: 'local' },
  { name: 'Docker', code: 'docker build -t app .', desc: 'Package app with all dependencies. Runs anywhere.', source: 'local' },
  { name: 'container', code: 'docker run app', desc: 'Isolated app from Docker. Like lightweight VM.', source: 'local' },
  { name: 'image', code: 'nginx:alpine', desc: 'Template for Docker container.', source: 'local' },
  { name: 'Kubernetes', code: 'kubectl apply -f deploy.yaml', desc: 'Manage many Docker containers. Short: K8s', source: 'local' },
  { name: 'env', code: 'process.env.NODE_ENV', desc: 'Environment. dev, staging, prod.', source: 'local' },
  { name: 'dotenv', code: 'require("dotenv").config()', desc: 'Load.env file into process.env', source: 'local' },
  { name: 'regex', code: '/^[A-Z]+$/', desc: 'Regular Expression. Pattern matching.', source: 'local' },
  { name: 'CLI', code: 'git status', desc: 'Command Line Interface. Use terminal.', source: 'local' },
  { name: 'GUI', code: 'VSCode window', desc: 'Graphical User Interface. Use mouse.', source: 'local' },
  { name: 'IDE', code: 'VSCode', desc: 'Integrated Development Environment. Code editor + tools. Example: VSCode, WebStorm', source: 'local' },
  { name: 'SDK', code: 'Android SDK', desc: 'Software Development Kit. Tools to build for platform.', source: 'local' },
  { name: 'framework', code: 'React', desc: 'Structure for app. You fill blanks. Example: React, Express', source: 'local' },
  { name: 'library', code: 'Lodash', desc: 'Code you call. Example: Lodash, Axios', source: 'local' },
  { name: 'debounce', code: 'setTimeout(fn, 300)', desc: 'Wait until user stops typing. Good for search.', source: 'local' },
  { name: 'throttle', code: 'run once per 100ms', desc: 'Limit function calls. Good for scroll/resize.', source: 'local' },
  { name: 'polyfill', code: 'Array.prototype.includes polyfill', desc: 'Code that adds new feature to old browser.', source: 'local' },
  { name: 'transpile', code: 'TS to JS', desc: 'Convert code to different version. Example: TS to JS', source: 'local' },
  { name: 'minify', code: 'terser file.js', desc: 'Remove spaces to make file smaller. For production.', source: 'local' },
  { name: 'uglify', code: 'uglifyjs file.js', desc: 'Minify + rename variables. Harder to read.', source: 'local' },
  { name: 'source map', code: 'app.js.map', desc: 'Maps minified code back to original. For debugging.', source: 'local' },
  { name: 'tree shaking', code: '// vite does this', desc: 'Remove unused code from bundle. Makes file smaller.', source: 'local' },
  { name: 'lazy load', code: 'const Page = lazy(() => import("./Page"))', desc: 'Load code only when needed. Improves initial speed.', source: 'local' },
  { name: 'SSR', code: 'Next.js getServerSideProps', desc: 'Server Side Rendering. HTML generated on server. Good for SEO.', source: 'local' },
  { name: 'CSR', code: 'React default', desc: 'Client Side Rendering. HTML generated in browser. Default React.', source: 'local' },
  { name: 'SSG', code: 'Next.js getStaticProps', desc: 'Static Site Generation. HTML built at build time. Fast.', source: 'local' },
  { name: 'PWA', code: 'manifest.json + sw.js', desc: 'Progressive Web App. Website that works like app. Offline support.', source: 'local' },
  { name: 'service worker', code: 'sw.js', desc: 'JS file for PWA. Runs in background. Handles cache, push.', source: 'local' },
  { name: 'manifest', code: 'manifest.json', desc: 'JSON file for PWA. Tells name, icon, colors.', source: 'local' },
  { name: 'webhook', code: 'POST to https://your-site.com/hook', desc: 'Server sends POST to your URL when event happens.', source: 'local' },
  { name: 'rate limit', code: 'express-rate-limit', desc: 'Limit API calls. Prevent abuse. Example: 100 requests per minute.', source: 'local' },
  { name: 'pagination', code: '?page=2&limit=10', desc: 'Split data into pages.', source: 'local' },
  { name: 'ORM', code: 'Prisma.findMany()', desc: 'Object Relational Mapper. Write DB queries in code. Example: Prisma, Sequelize', source: 'local' },
  { name: 'migration', code: 'npx prisma migrate dev', desc: 'Change database structure. Tracked in code.', source: 'local' },
  { name: 'seed', code: 'npx prisma db seed', desc: 'Fill database with test data.', source: 'local' },
  { name: 'monorepo', code: 'apps/ packages/', desc: 'Many projects in one git repo.', source: 'local' },
  { name: 'microservice', code: 'auth-service, user-service', desc: 'App split into small services. Each does one thing.', source: 'local' },
  { name: 'monolith', code: 'one big Express app', desc: 'All code in one app. Opposite of microservice.', source: 'local' },
  { name: 'agile', code: '2-week sprints', desc: 'Dev method. Small updates often. Sprints.', source: 'local' },
  { name: 'scrum', code: 'daily standup', desc: 'Agile framework. Daily standup, sprints, retro.', source: 'local' },
  { name: 'kanban', code: 'Trello board', desc: 'Visual task board. To Do, Doing, Done.', source: 'local' },
  { name: 'MVP', code: 'landing page + signup only', desc: 'Minimum Viable Product. Simplest version to test idea.', source: 'local' },
  { name: 'tech debt', code: '// TODO: refactor this', desc: 'Quick code now, pain later. Need to refactor.', source: 'local' },
  { name: 'refactor', code: 'rename function, extract component', desc: 'Change code without changing behavior. Make cleaner.', source: 'local' },
  { name: 'code review', code: 'GitHub PR review', desc: 'Teammate checks your code before merge.', source: 'local' },
  { name: 'unit test', code: 'test("adds 1+2", () => expect(add(1,2)).toBe(3))', desc: 'Test one function. Example: Jest', source: 'local' },
  { name: 'integration test', code: 'test API + DB', desc: 'Test multiple parts together.', source: 'local' },
  { name: 'e2e test', code: 'cy.visit("/login")', desc: 'End to end. Test full app like user. Example: Cypress', source: 'local' },
  { name: 'mock', code: 'jest.fn()', desc: 'Fake data for testing.', source: 'local' },
  { name: 'TDD', code: 'write test first', desc: 'Test Driven Development. Write test first, then code.', source: 'local' },
  { name: 'DRY', code: 'extract to function', desc: 'Do not Repeat Yourself. Avoid duplicate code.', source: 'local' },
  { name: 'KISS', code: 'use array instead of custom class', desc: 'Keep It Simple Stupid. Avoid complex solutions.', source: 'local' },
  { name: 'YAGNI', code: 'dont add caching yet', desc: 'You Are Not Gonna Need It. Do not add features until needed.', source: 'local' }
]